version: "3.9"

services:
  frontend:
    container_name: frontend-dev-docker
    image: frontend-dev-image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "start"]
