name: Dockerized Django CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Login to Docker Hub (Optional)
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Run Tests
      - name: Run Tests
        working-directory: django
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      # Step 4: Run Linter (Flake8)
      - name: Run Linter
        working-directory: django
        run: docker compose run --rm app sh -c "flake8"

      # Step 5: Build Docker Image
      - name: Build Docker Image
        working-directory: django
        run: docker build -t ${{ secrets.DOCKERHUB_USER }}/django_app:latest .

      # Step 7: Deploy to EC2 (Ubuntu)
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.RECIPE_HUB_KEY_AWS }}
          script: |
            # Update and Upgrade System
            sudo apt-get update -y
            sudo apt-get upgrade -y

            # Install Docker Using Official Script
            if ! [ -x "$(command -v docker)" ]; then
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo usermod -aG docker $USER
            fi

            # Install Docker Compose (if not installed)
            if ! [ -x "$(command -v docker-compose)" ]; then
              sudo apt-get install -y docker-compose
            fi

            # Configure Firewall (Allow HTTP/HTTPS traffic)
            sudo ufw allow OpenSSH
            sudo ufw allow 80/tcp
            sudo ufw allow 443/tcp
            sudo ufw --force enable

            # Stop and Remove Existing Containers
            sudo docker compose -f /home/ubuntu/django/docker-compose-deploy.yml down || true

            # Pull Latest Docker Image
            sudo docker pull ${{ secrets.DOCKERHUB_USER }}/django_app:latest

            # Start Application
            sudo docker compose -f /home/ubuntu/django/docker-compose-deploy.yml up -d --build

            # Verify Docker Containers Are Running
            sudo docker ps
