name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-check:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Login to Docker Hub (optional)
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Run Tests with Docker Compose
      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      # Step 4: Run Flake8 Linter with Docker Compose
      - name: Run Linter (Flake8)
        run: docker compose run --rm app sh -c "flake8"
