name: Dockerized Django CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Login to Docker Hub (Optional)
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Run Tests
      - name: Run Tests
        working-directory: django
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      # Step 4: Run Linter (Flake8)
      - name: Run Linter
        working-directory: django
        run: docker compose run --rm app sh -c "flake8"

      # Step 5: Build Docker Image
      - name: Build Docker Image
        working-directory: django
        run: docker build -t ${{ secrets.DOCKERHUB_USER }}/django_app:latest .

      # Step 7: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.RECIPE_HUB_KEY_AWS }}

          script: |
            # Update System
            sudo apt-get update -y
            sudo apt-get upgrade -y

            # Install Docker Using Official Script
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh

            # Stop and Remove Existing Containers
            docker compose -f /home/ubuntu/docker-compose.yml down || true

            # Pull Latest Docker Image
            docker pull ${{ secrets.DOCKERHUB_USER }}/django_app:latest

            # Start Application
            docker compose -f /home/ubuntu/docker-compose.yml up -d --build
