name: Dockerized Django CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set Up Docker
      - name: Set Up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      # Step 3: Login to Docker Hub (Optional)
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USER }}/django_app:latest .

      # Step 5: Push Docker Image to Docker Hub (Optional)
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/django_app:latest

      # Step 6: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.RECIPE_HUB_KEY_AWS }}
          script: |
            # Update System and Install Docker on EC2
            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose

            # Pull the Latest Docker Image
            docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ${{ secrets.DOCKERHUB_USER }}/django_app:latest

            # Stop and Remove Existing Containers (if any)
            docker compose -f /home/ubuntu/docker-compose.yml down || true

            # Start the Application with Docker Compose
            docker compose -f /home/ubuntu/docker-compose.yml up -d --build
